name: Build and Deploy Backend and Frontend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies (Backend)
        run: npm install
        working-directory: server  #  Fix: Run inside `server/`

      - name: Build backend (if needed)
        run: npm run build --if-present
        working-directory: server  #  Fix: Run inside `server/`

      # - name: Run tests (if applicable)
      #   run: npm run test --if-present
      #   working-directory: server  #  Fix: Run inside `server/`

      - name: Zip backend for deployment
        run: zip -r release.zip ./*
        working-directory: server  #  Fix: Only zip the backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: server/release.zip

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip backend artifact
        run: unzip release.zip

      - name: Deploy Backend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fire-warden-tracker-backend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_851B37D63A9C43A48675C1A2BE934A24 }}

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: client  # ✅ Fix: Run inside `client/`

      - name: Build Frontend
        run: npm run build
        working-directory: client  # ✅ Fix: Run inside `client/`

      - name: Deploy Frontend to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"         # ✅ Fix: Points to React app
          output_location: "client/build" # ✅ Fix: Build output location
